version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  bibbox-phenotips:
    image: bibbox/phenotips:1.4.9
    container_name:  bibbox-phenotips-fair
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - bibbox-phenotips-db:phenotips-db
    ports:
      - "8010:8080"
    depends_on:
      - bibbox-phenotips-db
    volumes: 
      - ./data/phenotips/extapi:/project/src 
  bibbox-phenotips-db:
    image: mariadb:10.7.3
    container_name: bibbox-phenotips-db-fair
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=phenotips
      - MYSQL_USER=phenotips
      - MYSQL_PASSWORD=phenotips4bibbox
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
     
  # fdp containers
  jupyter-openspecimen-fdp:
    image: jupyter/datascience-notebook:notebook-6.4.11
    container_name:  bibbox-phenotips-fair-jupyter
    links:
      - fdp-client:fdp-client
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - JUPYTER_TOKEN=FDP
      - FDP_TITLE=PhenoTips BIBBOX FDP
      - FDP_DESCRIPTION=FAIR Data Point (FDP) for the BIBBOX App PhenoTips.
      - FDP_PUBLICURL=http://localhost:8088
      - CATALOG_TITLE=Main Phenotips Catalog
      - CATALOG_VERSION=1.0
      - CATALOG_PUBLISHERNAME=BIBBOX
      - CATALOG_PUBLISHEREMAIL=admin@bibbox.org
      - CATALOG_PUBLISHERUID=https://github.com/bibbox
      - CATALOG_DESCRIPTION=Main Phenotips Catalog
      - CATALOG_LANGUAGE=http://id.loc.gov/vocabulary/iso639-1/en
      - CATALOG_HOMEPAGE=http://localhost:8010
      - DATASET_TITLE=Main Phenotips DATASET
      - DATASET_VERSION=1.0
      - DATASET_PUBLISHERNAME=BIBBOX
      - DATASET_PUBLISHEREMAIL=admin@bibbox.org
      - DATASET_PUBLISHERUID=https://github.com/bibbox
      - DATASET_DESCRIPTION=Main Phenotips DATASET
      - DATASET_LANGUAGE=http://id.loc.gov/vocabulary/iso639-1/en
      - DATASET_THEMES_LIST=http://theme.org/theme1;http://theme.org/theme2
      - DATASET_KEYWORDS=phenotips;phenotypes;family
      - DATASET_ISSUED=now
      - DATASET_LICENSE=http://license.org
      - DATASET_RIGHTS=http://rights.org
      - DATASET_CONTACTPOINT=admin@bibbox.org
      - DATASET_LANDINGPAGE=http://localhost:8010
      - DISTRIBUTION_TITLE=Main Phenotips DISTRIBUTION
      - DISTRIBUTION_VERSION=1.0
      - DISTRIBUTION_PUBLISHERNAME=BIBBOX
      - DISTRIBUTION_PUBLISHEREMAIL=admin@bibbox.org
      - DISTRIBUTION_PUBLISHERUID=https://github.com/bibbox
      - DISTRIBUTION_DESCRIPTION=Main Phenotips DISTRIBUTION
      - DISTRIBUTION_LANGUAGE=http://id.loc.gov/vocabulary/iso639-1/en
      - DISTRIBUTION_MEDIATYPE=text/html
      - DISTRIBUTION_ISSUED=now
      - DISTRIBUTION_LICENSE=http://license.org
      - DISTRIBUTION_RIGHTS=http://rights.org
      - DISTRIBUTION_ACCESSURL=http://localhost:8010
      
    ports:
        - "8888:8888"
    volumes:
        - ./data/jupyter/home/jovyan/work:/home/jovyan/work

  fdp:
    image: fairdata/fairdatapoint:1.13.1
    container_name:  bibbox-phenotips-fair-fdp
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "8080:80"
    volumes:
      - ./data/application.yml:/fdp/application.yml:ro
    links:
      - blazegraph:blazegraph
      - mongo:mongo
    environment:
      - CLIENTURL=http://localhost:8088
#    depends_on:
#      - virtuoso
#    environment:
#      - FDP_HOST=0.0.0.0
#      - FDP_PORT=8888
#    healthcheck:
#        test: curl --silent --fail http://0.0.0.0:$${FDP_PORT} || exit 1
#        interval: 5s
#    links:
#      - virtuoso:db

  fdp-client:
    image: fairdata/fairdatapoint-client:1.13.0
    container_name:  bibbox-phenotips-fair-fdp-client
    ports:
      - 8088:80
    environment:
      - FDP_HOST=fdp
    links:
      - fdp:fdp
    networks:
      - bibbox-default-network

  mongo:
    image: mongo:4.0.12
    container_name:  bibbox-phenotips-fair-fdp-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/data:/data/db
    networks:
      - bibbox-default-network

  blazegraph:
    image: metaphacts/blazegraph-basic:2.2.0-20160908.003514-6
    container_name:  bibbox-phenotips-fair-fdp-blazegraph
    ports:
      - 8081:8080
    volumes:
      - ./data/blazegraph:/blazegraph-data
    networks:
      - bibbox-default-network

